# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21243ea7056913904984f452e129547db6839fc5478c25e9773add152639b27a23c703325f13ba282935ec225c6fba0f57cd7778c5a8ad987fd9f496083786f2

test:
  secret_key_base: 29fdc7f78aa3c4df14ee6c56ea5cf0f1bfb4f50e39360e9ff9278f2ece380d939bbec38a3129ba0608d3a026980e2cf456dc43cab5ef035de6ee044b7bfb0a0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
